[log]
level = "debug"

[manifest]
url = "wudrm"
timeout_resolve_ms = 5000
timeout_connect_ms = 5000
timeout_send_ms = 10000
timeout_recv_ms = 10000

[stats]
enable_api = true

[lua]

[inject]
enabled = false

[cloud]
enabled = false

[remote]
